# Generated by Django 2.0.4 on 2019-12-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brake',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='设备mac地址'),
        ),
        migrations.AddField(
            model_name='camera',
            name='in_or_out',
            field=models.IntegerField(choices=[(0, '入'), (1, '出')], default=0, null=True, verbose_name='出或入'),
        ),
        migrations.AddField(
            model_name='camera',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='设备mac地址'),
        ),
        migrations.AddField(
            model_name='groundsensor',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='设备mac地址'),
        ),
    ]
