# Generated by Django 2.0.4 on 2019-12-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InAndOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='车牌')),
                ('color', models.CharField(max_length=100, verbose_name='车辆颜色')),
                ('logo', models.CharField(max_length=200, verbose_name='logo')),
                ('start_time', models.DateTimeField(null=True, verbose_name='识别时间')),
                ('park_id', models.CharField(max_length=200, verbose_name='park_id')),
                ('camera_id', models.CharField(max_length=200, verbose_name='camera_id')),
                ('picture', models.ImageField(null=True, upload_to='car', verbose_name='车辆图片')),
                ('closeup_pic', models.ImageField(null=True, upload_to='plate', verbose_name='车牌图片')),
            ],
            options={
                'verbose_name': '出入场记录',
                'verbose_name_plural': '出入场记录',
            },
        ),
    ]
