# Generated by Django 2.0.4 on 2019-12-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_auto_20191202_1237'),
        ('device', '0002_auto_20191203_1640'),
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inandout',
            name='camera_id',
        ),
        migrations.AddField(
            model_name='inandout',
            name='cam_id',
            field=models.CharField(max_length=200, null=True, verbose_name='camera_id(Mac地址)'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Camera', verbose_name='摄像头'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='parkinglot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkinglot.ParkingLot', verbose_name='车场'),
        ),
        migrations.AlterField(
            model_name='inandout',
            name='closeup_pic',
            field=models.ImageField(null=True, upload_to='plate/%Y/%m/%d', verbose_name='车牌图片'),
        ),
        migrations.AlterField(
            model_name='inandout',
            name='picture',
            field=models.ImageField(null=True, upload_to='car/%Y/%m/%d', verbose_name='车辆图片'),
        ),
    ]
