# Generated by Django 2.0.4 on 2019-12-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_auto_20191203_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='inandout',
            name='cam_ip',
            field=models.CharField(max_length=100, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='confidence',
            field=models.FloatField(null=True, verbose_name='置信度'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='plate_color',
            field=models.CharField(default='', max_length=100, verbose_name='车牌颜色'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inandout',
            name='plate_val',
            field=models.BooleanField(default=True, verbose_name='是否虚假车牌'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='triger_type',
            field=models.CharField(max_length=100, null=True, verbose_name='触发类型'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='vdc_type',
            field=models.CharField(max_length=100, null=True, verbose_name='出入口类型'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='vehicle_type',
            field=models.CharField(default='', max_length=100, verbose_name='车辆类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inandout',
            name='cam_id',
            field=models.CharField(max_length=100, null=True, verbose_name='camera_id(Mac地址)'),
        ),
        migrations.AlterField(
            model_name='inandout',
            name='park_id',
            field=models.CharField(max_length=100, verbose_name='park_id'),
        ),
    ]
