# Generated by Django 2.0.4 on 2019-12-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20191203_1640'),
        ('realtime', '0003_auto_20191205_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable', models.FloatField(verbose_name='应付金额')),
                ('payment', models.FloatField(verbose_name='实付金额')),
                ('pay_time', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('pay_type', models.IntegerField(choices=[(0, '现金'), (1, '微信'), (2, '支付宝'), (3, '刷卡')], null=True, verbose_name='支付方式')),
                ('parking_time', models.FloatField(null=True, verbose_name='停车时长(分钟)')),
                ('status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0)),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
            },
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='cam_id',
            new_name='cam_id_in',
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='cam_ip',
            new_name='cam_ip_in',
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='closeup_pic',
            new_name='closeup_pic_in',
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='confidence',
            new_name='confidence_in',
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='picture',
            new_name='picture_in',
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='plate_val',
            new_name='plate_val_in',
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='triger_type',
            new_name='triger_type_in',
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='vdc_type',
            new_name='vdc_type_in',
        ),
        migrations.RenameField(
            model_name='inandout',
            old_name='vehicle_type',
            new_name='vehicle_type_in',
        ),
        migrations.RemoveField(
            model_name='inandout',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='inandout',
            name='start_time',
        ),
        migrations.AddField(
            model_name='inandout',
            name='cam_id_out',
            field=models.CharField(max_length=100, null=True, verbose_name='camera_id(Mac地址)'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='cam_ip_out',
            field=models.CharField(max_length=100, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='camera_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_in', to='device.Camera', verbose_name='摄像头'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='camera_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_out', to='device.Camera', verbose_name='摄像头'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='closeup_pic_out',
            field=models.ImageField(null=True, upload_to='plate/%Y/%m/%d', verbose_name='车牌图片'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='color_in',
            field=models.CharField(default='', max_length=100, verbose_name='车辆颜色'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inandout',
            name='color_out',
            field=models.CharField(default='', max_length=100, verbose_name='车辆颜色'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inandout',
            name='confidence_out',
            field=models.FloatField(null=True, verbose_name='置信度'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='in_time',
            field=models.DateTimeField(null=True, verbose_name='入口识别时间'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='logo_in',
            field=models.CharField(default='', max_length=200, verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inandout',
            name='logo_out',
            field=models.CharField(default='', max_length=200, verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inandout',
            name='out_time',
            field=models.DateTimeField(null=True, verbose_name='出口识别时间'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='picture_out',
            field=models.ImageField(null=True, upload_to='car/%Y/%m/%d', verbose_name='车辆图片'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='plate_color_in',
            field=models.CharField(default='', max_length=100, verbose_name='车牌颜色'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inandout',
            name='plate_color_out',
            field=models.CharField(default='', max_length=100, verbose_name='车牌颜色'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inandout',
            name='plate_val_out',
            field=models.BooleanField(default=True, verbose_name='是否虚假车牌'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='triger_type_out',
            field=models.CharField(max_length=100, null=True, verbose_name='触发类型'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='vdc_type_out',
            field=models.CharField(max_length=100, null=True, verbose_name='出入口类型'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='vehicle_type_out',
            field=models.CharField(default='', max_length=100, verbose_name='车辆类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='in_and_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.InAndOut', verbose_name='停车记录'),
        ),
    ]
