# Generated by Django 2.0.4 on 2019-12-06 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_auto_20191206_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='in_and_out',
        ),
        migrations.RemoveField(
            model_name='inandout',
            name='color',
        ),
        migrations.RemoveField(
            model_name='inandout',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='inandout',
            name='plate_color',
        ),
        migrations.AddField(
            model_name='inandout',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.Bill', verbose_name='账单'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 6, 17, 10, 26, 607178), verbose_name='更新时间'),
            preserve_default=False,
        ),
    ]
