# Generated by Django 2.0.4 on 2019-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0005_auto_20191206_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inandout',
            old_name='vdc_type_in',
            new_name='vdc_type',
        ),
        migrations.RemoveField(
            model_name='inandout',
            name='vdc_type_out',
        ),
    ]
