# Generated by Django 2.2.3 on 2019-12-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_adminuser_status'),
        ('realtime', '0006_auto_20191206_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='收费时间')),
                ('type', models.IntegerField(choices=[(0, '全部'), (1, '手动免费开闸'), (2, '异常出车'), (3, '现金支付')], default=0, verbose_name='收费类型')),
                ('price', models.FloatField(default=0, null=True, verbose_name='应收费用')),
                ('real_price', models.FloatField(default=0, verbose_name='实收费用')),
            ],
            options={
                'verbose_name': '收费明细',
                'verbose_name_plural': '收费明细',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=30, null=True, verbose_name='车牌号')),
                ('arrive_time', models.DateTimeField(null=True, verbose_name='入场时间')),
                ('leave_time', models.DateTimeField(null=True, verbose_name='离场时间')),
                ('duration', models.FloatField(null=True, verbose_name='停车时长')),
                ('car_type', models.CharField(max_length=30, null=True, verbose_name='车辆类型')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail', to='realtime.PayDetail', verbose_name='收费明细')),
                ('tollman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.AdminUser', verbose_name='收费员')),
            ],
            options={
                'verbose_name': '付费记录',
                'verbose_name_plural': '付费记录',
            },
        ),
    ]
