# Generated by Django 2.0.4 on 2019-12-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_merge_20190812_0048'),
        ('realtime', '0006_auto_20191206_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='inandout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.User', verbose_name='停车用户'),
        ),
    ]
