# Generated by Django 2.0.4 on 2019-12-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_merge_20190812_0048'),
        ('realtime', '0007_inandout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.Order'),
        ),
    ]
