# Generated by Django 2.2.3 on 2019-12-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0008_auto_20191209_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='arrive_time',
            new_name='arrived_time',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='leave_time',
            new_name='left_time',
        ),
    ]
