# Generated by Django 2.2.3 on 2019-12-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0009_auto_20191209_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='tollman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkinglot.Worker', verbose_name='收费员'),
        ),
    ]
