# Generated by Django 2.2.3 on 2019-12-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_auto_20191202_1237'),
        ('realtime', '0010_auto_20191209_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail', to='realtime.PayDetail', verbose_name='收费明细'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tollman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkinglot.Worker', verbose_name='收费员'),
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
