# Generated by Django 2.2.3 on 2019-12-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0013_auto_20191209_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inandout',
            name='bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='InAndOut', to='realtime.Bill', verbose_name='账单'),
        ),
    ]
