# Generated by Django 2.0.4 on 2019-12-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0014_auto_20191209_1730'),
        ('realtime', '0009_auto_20191211_1553'),
    ]

    operations = [
    ]
