# Generated by Django 2.0.4 on 2019-12-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20191203_1640'),
        ('parkinglot', '0003_auto_20191202_1237'),
        ('realtime', '0017_auto_20191212_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '关闭'), (1, '打开'), (2, '需要打开')], default=0)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Camera')),
                ('gate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.Gate')),
                ('parkinglot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot')),
            ],
            options={
                'verbose_name': '开闸指令',
                'verbose_name_plural': '开闸指令',
            },
        ),
        migrations.AddField(
            model_name='inandout',
            name='enter_type',
            field=models.IntegerField(choices=[(0, '车牌识别'), (1, '扫码抬杆')], default=0, verbose_name='入场类型'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='final_out_time',
            field=models.DateTimeField(null=True, verbose_name='实际出场时间'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='gate_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_in', to='parkinglot.Gate', verbose_name='入口'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='gate_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_out', to='parkinglot.Gate', verbose_name='出口'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='leave_type',
            field=models.IntegerField(choices=[(0, '车牌识别'), (1, '扫码抬杆')], default=0, verbose_name='出场类型'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='status',
            field=models.IntegerField(choices=[(0, '入场'), (1, '出场')], default=0, verbose_name='车辆状态'),
        ),
        migrations.AlterField(
            model_name='inandout',
            name='out_time',
            field=models.DateTimeField(null=True, verbose_name='出场时间(用户端点击出场)'),
        ),
    ]
