# Generated by Django 2.0.4 on 2019-12-12 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0018_auto_20191212_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingorder',
            name='in_and_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realtime.InAndOut'),
        ),
    ]
