# Generated by Django 2.0.4 on 2019-12-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0019_openingorder_in_and_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inandout',
            name='status',
            field=models.IntegerField(choices=[(-1, '待入场'), (0, '入场'), (1, '出场')], default=0, verbose_name='车辆状态'),
        ),
    ]
