# Generated by Django 2.2.3 on 2019-12-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0021_auto_20191217_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inandout',
            old_name='id_spec',
            new_name='is_spec',
        ),
    ]
