# Generated by Django 2.2.3 on 2019-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0024_auto_20191219_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inandout',
            name='exception',
            field=models.IntegerField(choices=[(0, '正常'), (1, '异常')], default=0),
        ),
    ]
