# Generated by Django 2.2.3 on 2019-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0025_auto_20191219_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptrecord',
            name='direction',
            field=models.IntegerField(choices=[(0, '出'), (1, '入')], default=0, verbose_name='方向'),
        ),
    ]
