# Generated by Django 2.2.3 on 2019-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0026_auto_20191219_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '已处理')], default=0, verbose_name='状态'),
        ),
    ]
