# Generated by Django 2.2.3 on 2019-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0027_exceptrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已出场')], default=0),
        ),
    ]
