# Generated by Django 2.2.3 on 2019-12-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0028_auto_20191223_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceptrecord',
            old_name='time',
            new_name='update_time',
        ),
    ]
