# Generated by Django 2.2.3 on 2019-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0030_auto_20191224_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inandout',
            name='status',
            field=models.IntegerField(choices=[(-1, '待入场'), (0, '入场'), (1, '已出场')], default=0, verbose_name='车辆状态'),
        ),
    ]
