# Generated by Django 2.0.4 on 2019-12-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0031_auto_20191224_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='inandout',
            name='bill2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.Bill', verbose_name='滞留费'),
        ),
        migrations.AddField(
            model_name='inandout',
            name='latest_leave_time',
            field=models.DateTimeField(null=True, verbose_name='最晚离场时间(超出则产生滞留费)'),
        ),
        migrations.AlterField(
            model_name='inandout',
            name='out_time',
            field=models.DateTimeField(null=True, verbose_name='出场时间(用户端点击出场结算)'),
        ),
    ]
