# Generated by Django 2.0.4 on 2019-12-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0032_auto_20191227_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inandout',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='InAndOut', to='realtime.Bill', verbose_name='账单'),
        ),
        migrations.AlterField(
            model_name='inandout',
            name='bill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.Bill', verbose_name='滞留费'),
        ),
    ]
