# Generated by Django 2.0.4 on 2020-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0044_auto_20200106_1431'),
        ('realtime', '0033_auto_20191230_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='user_coupon',
            field=models.ManyToManyField(to='chargerule.UserCoupon', verbose_name='用券'),
        ),
    ]
