# Generated by Django 2.2.3 on 2019-12-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0009_auto_20191209_0932'),
        ('chargerule', '0032_ticketrecord_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '使用中'), (2, '审核失败')], default=0, verbose_name='状态')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company', verbose_name='商家')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargerule.Coupons', verbose_name='券')),
            ],
            options={
                'verbose_name': '申请记录',
                'verbose_name_plural': '申请记录',
            },
        ),
    ]
