# Generated by Django 2.2.3 on 2019-12-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_merge_20190812_0048'),
        ('business', '0002_businessbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrecord',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.BusinessBill', verbose_name='商户账单'),
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='extra',
            field=models.IntegerField(default=0, verbose_name='余量'),
        ),
        migrations.AddField(
            model_name='businessbill',
            name='cost',
            field=models.FloatField(default=0, verbose_name='费用'),
        ),
        migrations.AddField(
            model_name='businessbill',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessbill',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.Product'),
        ),
        migrations.AddField(
            model_name='businessbill',
            name='status',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '已支付')], default=0, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargerule.TicketRecord', verbose_name='券'),
        ),
    ]
