# Generated by Django 2.2.3 on 2019-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20191227_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='businessbill',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
