# Generated by Django 2.2.3 on 2019-12-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20191227_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyrecord',
            name='extra',
        ),
        migrations.AlterField(
            model_name='businessbill',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.Product'),
        ),
    ]
