# Generated by Django 2.2.3 on 2019-12-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20191227_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyrecord',
            name='company',
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '使用中'), (2, '未通过')], default=0, verbose_name='状态'),
        ),
    ]
