# Generated by Django 2.2.3 on 2019-12-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20191227_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '使用中'), (2, '未通过')], default=1, verbose_name='状态'),
        ),
    ]
