# Generated by Django 2.0.4 on 2019-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('hours', models.FloatField(blank=True, null=True, verbose_name='小时数')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('detail', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '抵扣券',
                'verbose_name_plural': '抵扣券',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='折扣率')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('detail', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '打折券',
                'verbose_name_plural': '打折券',
            },
        ),
        migrations.CreateModel(
            name='HourTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money1', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('hours1', models.FloatField(blank=True, null=True, verbose_name='小时数')),
                ('money2', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('hours2', models.FloatField(blank=True, null=True, verbose_name='小时数')),
                ('money3', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('hours3', models.FloatField(blank=True, null=True, verbose_name='小时数')),
                ('money4', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('hours4', models.FloatField(blank=True, null=True, verbose_name='小时数')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('detail', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '满时券',
                'verbose_name_plural': '满时券',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True, verbose_name='金额')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('detail', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '代金券',
                'verbose_name_plural': '代金券',
            },
        ),
    ]
