# Generated by Django 2.2.3 on 2019-11-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('chargerule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('valid_start', models.CharField(max_length=30, null=True, verbose_name='有效开始')),
                ('valid_end', models.CharField(max_length=30, null=True, verbose_name='有效结束')),
                ('holidays', models.TextField(blank=True, null=True, verbose_name='非工作日')),
            ],
            options={
                'verbose_name': '普通月卡',
                'verbose_name_plural': '普通月卡',
            },
        ),
        migrations.CreateModel(
            name='RerveseCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('valid_start', models.CharField(max_length=30, null=True, verbose_name='有效开始')),
                ('valid_end', models.CharField(max_length=30, null=True, verbose_name='有效结束')),
                ('valid_start1', models.CharField(max_length=30, null=True, verbose_name='有效开始')),
                ('valid_end1', models.CharField(max_length=30, null=True, verbose_name='有效结束')),
                ('holidays', models.TextField(blank=True, null=True, verbose_name='非工作日')),
            ],
            options={
                'verbose_name': '错峰卡',
                'verbose_name_plural': '错峰卡',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('normalcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chargerule.RerveseCard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.AdminUser')),
            ],
            options={
                'verbose_name': '商家普通月卡',
            },
        ),
    ]
