# Generated by Django 2.2.3 on 2019-11-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('parkinglot', '0002_auto_20191127_1210'),
        ('chargerule', '0002_normalcard_rervesecard_usercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('valid_start', models.TextField(blank=True, null=True, verbose_name='有效开始')),
                ('valid_end', models.TextField(blank=True, null=True, verbose_name='有效结束')),
                ('holidays', models.TextField(blank=True, null=True, verbose_name='非工作日')),
                ('my_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chargerule.Card')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.AdminUser')),
            ],
            options={
                'verbose_name': '月卡',
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('rule', models.CharField(max_length=100, null=True, verbose_name='描述')),
                ('suit', models.ManyToManyField(null=True, to='parkinglot.ParkingLot', verbose_name='可用停车场')),
            ],
            options={
                'verbose_name': '月卡类型',
                'verbose_name_plural': '月卡类型',
            },
        ),
        migrations.DeleteModel(
            name='NormalCard',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='normalcard',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='user',
        ),
        migrations.DeleteModel(
            name='RerveseCard',
        ),
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
