# Generated by Django 2.2.3 on 2019-11-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0003_auto_20191129_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='suit',
            field=models.ManyToManyField(to='parkinglot.ParkingLot', verbose_name='可用停车场'),
        ),
    ]
