# Generated by Django 2.2.3 on 2019-11-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0005_auto_20191129_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='valid_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有效结束'),
        ),
        migrations.AlterField(
            model_name='card',
            name='valid_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有效开始'),
        ),
    ]
