# Generated by Django 2.0.4 on 2019-11-29 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0005_auto_20191129_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_delete',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='rule',
            field=models.CharField(default='', max_length=200, verbose_name='细则'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_delete',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='rule',
            field=models.CharField(default=datetime.datetime(2019, 11, 29, 10, 46, 9, 446770), max_length=200, verbose_name='细则'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hourticket',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hourticket',
            name='is_delete',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AddField(
            model_name='hourticket',
            name='rule',
            field=models.CharField(default='', max_length=200, verbose_name='细则'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourticket',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_delete',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='rule',
            field=models.CharField(default='', max_length=200, verbose_name='细则'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
