# Generated by Django 2.2.3 on 2019-11-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0006_auto_20191129_1206'),
        ('chargerule', '0006_auto_20191129_1046'),
    ]

    operations = [
    ]
