# Generated by Django 2.0.4 on 2019-11-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20191128_1909'),
        ('parkinglot', '0002_auto_20191127_1210'),
        ('chargerule', '0007_merge_20191129_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.IntegerField(choices=[(0, '折扣券'), (1, '代金券'), (2, '抵扣券'), (3, '满时券')])),
                ('buy_time', models.DateTimeField(null=True, verbose_name='购买时间')),
                ('amount', models.IntegerField(null=True, verbose_name='购买数量')),
                ('start_date', models.DateTimeField(null=True, verbose_name='起始日期')),
                ('end_date', models.DateTimeField(null=True, verbose_name='截止日期')),
                ('start_time1', models.FloatField(null=True, verbose_name='优惠时段起点')),
                ('end_time1', models.FloatField(null=True, verbose_name='优惠时段截止')),
                ('start_time2', models.FloatField(null=True, verbose_name='优惠时段起点')),
                ('end_time2', models.FloatField(null=True, verbose_name='优惠时段截止')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargerule.Coupon')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargerule.Discount')),
                ('hourticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargerule.HourTicket')),
                ('parkinglot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkinglot.ParkingLot')),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargerule.Voucher')),
            ],
            options={
                'verbose_name': '优惠券出售记录',
                'verbose_name_plural': '优惠券出售记录',
            },
        ),
    ]
