# Generated by Django 2.2.3 on 2019-11-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0008_auto_20191129_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='work_start',
            field=models.CharField(max_length=30, null=True, verbose_name='工作结束'),
        ),
    ]
