# Generated by Django 2.2.3 on 2019-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0009_card_work_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='holidays',
        ),
        migrations.AddField(
            model_name='card',
            name='workdays',
            field=models.TextField(blank=True, null=True, verbose_name='工作日'),
        ),
    ]
