# Generated by Django 2.2.3 on 2019-11-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0011_card_holidays'),
        ('chargerule', '0008_ticketrecord'),
    ]

    operations = [
    ]
