# Generated by Django 2.2.3 on 2019-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0012_merge_20191129_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='rule',
        ),
        migrations.AddField(
            model_name='cardtype',
            name='relax_end',
            field=models.DateTimeField(null=True, verbose_name='休息结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='relax_start',
            field=models.DateTimeField(null=True, verbose_name='休息开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='work_end',
            field=models.DateTimeField(null=True, verbose_name='工作结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='work_start',
            field=models.DateTimeField(null=True, verbose_name='工作开始'),
        ),
    ]
