# Generated by Django 2.2.3 on 2019-12-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0013_auto_20191202_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='suit',
        ),
    ]
