# Generated by Django 2.2.3 on 2019-12-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0015_auto_20191202_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='work_start',
        ),
    ]
