# Generated by Django 2.2.3 on 2019-12-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0016_remove_card_work_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='diff_type',
            field=models.IntegerField(choices=[(0, '工作日'), (1, '单日')], null=True, verbose_name='减免指标'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_end',
            field=models.CharField(max_length=30, null=True, verbose_name='周一优惠结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_end_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='周五优惠结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_end_sa',
            field=models.CharField(max_length=30, null=True, verbose_name='周六优惠结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_end_su',
            field=models.CharField(max_length=30, null=True, verbose_name='周日优惠结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_end_th',
            field=models.CharField(max_length=30, null=True, verbose_name='周四优惠结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_end_tu',
            field=models.CharField(max_length=30, null=True, verbose_name='周二优惠结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_end_we',
            field=models.CharField(max_length=30, null=True, verbose_name='周三优惠结束'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_start',
            field=models.CharField(max_length=30, null=True, verbose_name='周一优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_start_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='周五优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_start_sa',
            field=models.CharField(max_length=30, null=True, verbose_name='周六优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_start_su',
            field=models.CharField(max_length=30, null=True, verbose_name='周日优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_start_th',
            field=models.CharField(max_length=30, null=True, verbose_name='周四优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_start_tu',
            field=models.CharField(max_length=30, null=True, verbose_name='周二优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_start_we',
            field=models.CharField(max_length=30, null=True, verbose_name='周三优惠开始'),
        ),
    ]
