# Generated by Django 2.2.3 on 2019-12-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_auto_20191202_1237'),
        ('chargerule', '0017_auto_20191202_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='holidays',
        ),
        migrations.RemoveField(
            model_name='card',
            name='workdays',
        ),
        migrations.AddField(
            model_name='card',
            name='suit',
            field=models.ManyToManyField(to='parkinglot.ParkingLot', verbose_name='所属停车场'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='diff_type',
            field=models.IntegerField(choices=[(0, '工作日'), (1, '单日')], default=0, null=True, verbose_name='减免指标'),
        ),
    ]
