# Generated by Django 2.2.3 on 2019-12-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0018_auto_20191203_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.ManyToManyField(related_name='parkinglot_card', to='parkinglot.ParkingLot', verbose_name='所属停车场'),
        ),
    ]
