# Generated by Django 2.2.3 on 2019-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0019_auto_20191203_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='is_diff',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, max_length=30),
        ),
    ]
