# Generated by Django 2.2.3 on 2019-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0021_auto_20191204_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='car_number',
            field=models.CharField(max_length=30, null=True, verbose_name='车牌号'),
        ),
    ]
