# Generated by Django 2.2.3 on 2019-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0022_card_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='联系人电话'),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.CharField(max_length=30, null=True, verbose_name='持卡人'),
        ),
    ]
