# Generated by Django 2.2.3 on 2019-12-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0024_remove_cardtype_is_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='free_end',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_end_fr',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_end_sa',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_end_su',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_end_th',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_end_tu',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_end_we',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_start',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_start_fr',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_start_sa',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_start_su',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_start_th',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_start_tu',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='free_start_we',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='relax_end',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='relax_start',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='work_start',
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free',
            field=models.TextField(max_length=30, null=True, verbose_name='周一优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_fr',
            field=models.TextField(max_length=30, null=True, verbose_name='周五优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_sa',
            field=models.TextField(max_length=30, null=True, verbose_name='周六优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_su',
            field=models.TextField(max_length=30, null=True, verbose_name='周日优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_th',
            field=models.TextField(max_length=30, null=True, verbose_name='周四优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_tu',
            field=models.TextField(max_length=30, null=True, verbose_name='周二优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='free_we',
            field=models.TextField(max_length=30, null=True, verbose_name='周三优惠开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='relax',
            field=models.TextField(max_length=30, null=True, verbose_name='休息开始'),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='work',
            field=models.TextField(max_length=30, null=True, verbose_name='工作开始'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='name',
            field=models.TextField(max_length=30, verbose_name='名称'),
        ),
    ]
