# Generated by Django 2.2.3 on 2019-12-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0026_auto_20191206_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='diff_type',
            field=models.IntegerField(choices=[(0, '工作日'), (1, '自定义')], default=0, null=True, verbose_name='减免指标'),
        ),
    ]
