# Generated by Django 2.2.3 on 2019-12-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_auto_20191202_1237'),
        ('chargerule', '0027_auto_20191206_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('per_hour', models.FloatField(default=0, verbose_name='小时费')),
                ('free_time', models.IntegerField(default=0, verbose_name='免费时间')),
                ('day_max', models.FloatField(default=0, verbose_name='单日最大费用时段')),
                ('min_price', models.IntegerField(default=0, verbose_name='最短计价时间')),
                ('parkinglot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkinglot.ParkingLot')),
            ],
            options={
                'verbose_name': '基础规则',
                'verbose_name_plural': '基础规则',
            },
        ),
    ]
