# Generated by Django 2.0.4 on 2019-12-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0029_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrecord',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='ticketrecord',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='ticketrecord',
            name='hourticket',
        ),
        migrations.RemoveField(
            model_name='ticketrecord',
            name='voucher',
        ),
        migrations.AddField(
            model_name='ticketrecord',
            name='coupons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargerule.Coupons'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='HourTicket',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
