# Generated by Django 2.2.3 on 2019-12-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0030_auto_20191209_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='联系人电话'),
        ),
    ]
