# Generated by Django 2.0.4 on 2019-12-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_merge_20190812_0048'),
        ('chargerule', '0031_auto_20191220_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='车牌')),
                ('status', models.IntegerField(choices=[(0, '未使用'), (1, '已使用')])),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('use_time', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargerule.Coupons')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.User')),
            ],
            options={
                'verbose_name': '用户和券',
                'verbose_name_plural': '用户和券',
            },
        ),
    ]
