# Generated by Django 2.2.3 on 2019-12-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0032_usercoupon'),
        ('chargerule', '0032_ticketrecord_extra'),
    ]

    operations = [
    ]
