# Generated by Django 2.2.3 on 2019-12-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0033_merge_20191226_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrecord',
            name='coucode',
            field=models.ImageField(null=True, upload_to='coucode/', verbose_name='券码'),
        ),
    ]
