# Generated by Django 2.2.3 on 2019-12-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0035_auto_20191227_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrecord',
            name='extra',
        ),
    ]
