# Generated by Django 2.2.3 on 2019-12-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0036_remove_ticketrecord_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrecord',
            name='extra',
            field=models.IntegerField(default=0, verbose_name='余量'),
        ),
    ]
