# Generated by Django 2.2.3 on 2019-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0037_ticketrecord_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrecord',
            name='superpose',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否可叠加'),
        ),
    ]
