# Generated by Django 2.2.3 on 2019-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargerule', '0039_ticketrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '已通过'), (2, '审核失败')], default=0),
        ),
    ]
