# Generated by Django 2.0.4 on 2020-01-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta', '0008_merge_20190812_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=100, verbose_name='车牌')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.User')),
            ],
            options={
                'verbose_name': '我的车牌',
            },
        ),
    ]
