# Generated by Django 2.2.3 on 2020-01-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20200102_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='create_time',
            new_name='update_time',
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '已处理')], default=0),
        ),
    ]
