# Generated by Django 2.0.4 on 2019-11-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='菜单名称'),
        ),
        migrations.AddField(
            model_name='menu',
            name='operation',
            field=models.ManyToManyField(to='administrator.Operation', verbose_name='操作'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='相对路径url'),
        ),
        migrations.AddField(
            model_name='operation',
            name='action',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='方法名'),
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='操作名称'),
        ),
    ]
