# Generated by Django 2.2.3 on 2019-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='real_name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user_pass',
            field=models.CharField(max_length=30, verbose_name='密码'),
        ),
    ]
