# Generated by Django 2.2.3 on 2019-12-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20191202_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
