# Generated by Django 2.2.3 on 2019-12-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_adminuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='电话号码'),
        ),
    ]
