# Generated by Django 2.2.3 on 2019-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20191126_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='action',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='operation_name',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='status',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
    ]
