# Generated by Django 2.2.3 on 2019-11-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_parkinglot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingLot',
        ),
    ]
