# Generated by Django 2.0.4 on 2019-11-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_delete_parkinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='操作内容'),
        ),
        migrations.AddField(
            model_name='log',
            name='create_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='log',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='操作模块'),
        ),
        migrations.AddField(
            model_name='log',
            name='operation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='操作'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.AdminUser', verbose_name='操作用户'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['create_day'], name='create_day_idx'),
        ),
    ]
