# Generated by Django 2.0.4 on 2019-11-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20191126_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='status',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='菜单名称'),
        ),
        migrations.AddField(
            model_name='menu',
            name='operation',
            field=models.ManyToManyField(to='administrator.Operation', verbose_name='操作'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='相对路径url'),
        ),
        migrations.AddField(
            model_name='operation',
            name='action',
            field=models.CharField(default='', max_length=100, verbose_name='方法名'),
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_name',
            field=models.CharField(default='', max_length=100, verbose_name='操作名称'),
        ),
        migrations.AddField(
            model_name='authority',
            name='child_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_menu', to='administrator.Menu', verbose_name='二级菜单'),
        ),
        migrations.AddField(
            model_name='authority',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_menu', to='administrator.Menu', verbose_name='以及菜单'),
        ),
        migrations.AddField(
            model_name='authority',
            name='operation',
            field=models.ManyToManyField(to='administrator.Operation'),
        ),
        migrations.AddField(
            model_name='authority',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Role', verbose_name='角色'),
        ),
    ]
