# Generated by Django 2.0.4 on 2019-11-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('use_type', models.IntegerField(choices=[(0, '停车场内'), (1, '停车场入口'), (2, '停车场出口')], default=0, verbose_name='使用类型')),
                ('ctrl_type', models.IntegerField(choices=[(0, '临停车控制'), (1, '入口不控制'), (2, '控制入车类型'), (3, '不控制只抓拍'), (4, '时间控制'), (5, '月租车控制'), (6, '卡票控制')], default=0, verbose_name='控制类型')),
                ('zone', models.IntegerField(choices=[(0, '地面'), (1, '地库')], default=0, verbose_name='所属区域')),
                ('monitor', models.CharField(blank=True, max_length=30, verbose_name='所属监控')),
                ('charge_rule', models.IntegerField(choices=[(0, '按出口所在区域收费'), (1, '按入口所在区域收费')], default=0, verbose_name='收费规则')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30, verbose_name='停车场名称')),
                ('zone_num', models.IntegerField(default=0, verbose_name='区域数')),
                ('place_num', models.IntegerField(default=0, verbose_name='车位数')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('car_type', models.CharField(choices=[(0, '小型车'), (1, '中型车'), (2, '大型车')], max_length=30, null=True, verbose_name='车辆类型')),
                ('use_type', models.IntegerField(choices=[(0, '临停车'), (1, '长租车')], default=0, null=True, verbose_name='使用类型')),
                ('parkinglot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='所属车场')),
            ],
            options={
                'verbose_name': '泊位管理',
                'verbose_name_plural': '泊位管理',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='员工号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='员工名称')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('forbidden', models.IntegerField(choices=[(0, '启用'), (1, '禁用')], default=0, verbose_name='是否禁用')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('parkinglot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkinglot.ParkingLot', verbose_name='所属车场')),
            ],
            options={
                'verbose_name': '车场员工',
                'verbose_name_plural': '车场员工',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('zone_name', models.CharField(max_length=30, null=True, verbose_name='区域名称')),
                ('place_num', models.IntegerField(default=0, null=True, verbose_name='泊位数')),
                ('parkinglot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='所属车场')),
            ],
            options={
                'verbose_name': '区域管理',
                'verbose_name_plural': '区域管理',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.Zone', verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='gate',
            name='parkinglot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='所属车场'),
        ),
    ]
