# Generated by Django 2.2.3 on 2019-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='停车场名称')),
                ('zone_num', models.IntegerField(default=0, unique=True, verbose_name='区域数')),
                ('place_num', models.IntegerField(default=0, unique=True, verbose_name='车位数')),
            ],
        ),
    ]
