# Generated by Django 2.2.3 on 2019-11-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
