# Generated by Django 2.0.4 on 2019-11-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='员工号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='员工名称')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否删除')),
                ('forbidden', models.IntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否禁用')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('parkinglot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkinglot.ParkingLot', verbose_name='所属车场')),
            ],
            options={
                'verbose_name': '车场员工',
                'verbose_name_plural': '车场员工',
            },
        ),
    ]
