# Generated by Django 2.0.4 on 2019-11-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_worker'),
        ('parkinglot', '0002_auto_20191126_1709'),
    ]

    operations = [
    ]
