# Generated by Django 2.2.3 on 2019-12-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_auto_20191127_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='use_type',
            field=models.IntegerField(choices=[(0, '临停车'), (1, '月租车')], default=0, null=True, verbose_name='使用类型'),
        ),
    ]
