# Generated by Django 2.2.3 on 2019-12-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_auto_20191202_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='code',
            field=models.ImageField(null=True, upload_to='qrcode/', verbose_name='二维码'),
        ),
    ]
