# Generated by Django 2.2.3 on 2019-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0004_auto_20191126_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='ctrl_type',
            field=models.IntegerField(choices=[(0, '临停车控制'), (1, '入口不控制'), (2, '控制入车类型'), (3, '不控制只抓拍'), (4, '时间控制'), (5, '月租车控制'), (6, '卡票控制')], default=0, verbose_name='控制类型'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='use_type',
            field=models.IntegerField(choices=[(0, '停车场内'), (1, '停车场入口'), (2, '停车场出口')], default=0, verbose_name='使用类型'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='zone',
            field=models.IntegerField(choices=[(0, '地面'), (1, '地库')], default=0, verbose_name='所属区域'),
        ),
    ]
