# Generated by Django 2.2.3 on 2019-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0005_auto_20191126_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='place_num',
            field=models.IntegerField(default=0, verbose_name='车位数'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='zone_num',
            field=models.IntegerField(default=0, verbose_name='区域数'),
        ),
    ]
