# Generated by Django 2.0.4 on 2019-12-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0005_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='parkinglot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot'),
        ),
    ]
