# Generated by Django 2.2.3 on 2019-11-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_worker'),
        ('parkinglot', '0006_auto_20191126_1856'),
    ]

    operations = [
    ]
