# Generated by Django 2.2.3 on 2019-11-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0007_merge_20191126_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='区域名称')),
                ('place_num', models.IntegerField(default=0, verbose_name='泊位数')),
                ('parkinglot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkinglot.ParkingLot', verbose_name='所属车场')),
            ],
            options={
                'verbose_name': '区域管理',
                'verbose_name_plural': '区域管理',
            },
        ),
    ]
