# Generated by Django 2.2.3 on 2019-12-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0007_worker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='名称'),
        ),
    ]
