# Generated by Django 2.2.3 on 2019-11-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0008_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='name',
            new_name='zone_name',
        ),
    ]
