# Generated by Django 2.0.4 on 2019-11-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_merge_20191126_1721'),
        ('parkinglot', '0009_auto_20191126_1945'),
    ]

    operations = [
    ]
