# Generated by Django 2.2.3 on 2019-11-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_merge_20191126_1721'),
        ('parkinglot', '0010_auto_20191127_0935'),
    ]

    operations = [
    ]
