# Generated by Django 2.0.4 on 2019-11-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0011_merge_20191127_0945'),
        ('parkinglot', '0010_merge_20191127_0951'),
    ]

    operations = [
    ]
