# Generated by Django 2.2.3 on 2019-11-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0012_merge_20191127_0952'),
        ('parkinglot', '0012_auto_20191127_1144'),
    ]

    operations = [
    ]
