# Generated by Django 2.0.4 on 2019-11-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0012_auto_20191127_1144'),
        ('parkinglot', '0012_merge_20191127_0952'),
    ]

    operations = [
    ]
