# Generated by Django 2.2.3 on 2019-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0013_merge_20191127_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='car_type',
            field=models.IntegerField(choices=[(0, '小型车'), (1, '中型车'), (2, '大型车')], max_length=30, null=True, verbose_name='车辆类型'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='forbidden',
            field=models.IntegerField(choices=[(0, '启用'), (1, '禁用')], default=0, verbose_name='是否禁用'),
        ),
    ]
