# Generated by Django 2.2.3 on 2019-11-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0013_merge_20191127_1149'),
        ('parkinglot', '0015_auto_20191127_1153'),
    ]

    operations = [
    ]
