# Generated by Django 2.2.3 on 2019-12-13 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_merge_20190812_0048'),
        ('realtime', '0020_auto_20191213_0932'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.CharField(max_length=100, verbose_name='放行原因')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.InAndOut', verbose_name='出入场记录')),
                ('tollman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.User', verbose_name='收费员')),
            ],
            options={
                'verbose_name': '特殊放行记录',
                'verbose_name_plural': '特殊放行记录',
            },
        ),
        migrations.DeleteModel(
            name='account_record',
        ),
    ]
