# Generated by Django 2.2.3 on 2019-12-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191213_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True, verbose_name='上岗时间')),
                ('duration', models.FloatField(default=0, verbose_name='值班时长')),
                ('spec_num', models.IntegerField(default=0, verbose_name='特放车辆')),
            ],
            options={
                'verbose_name': '值班记录',
                'verbose_name_plural': '值班记录',
            },
        ),
        migrations.DeleteModel(
            name='SpecialPass',
        ),
    ]
