# Generated by Django 2.2.3 on 2019-12-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_merge_20190812_0048'),
        ('account', '0003_auto_20191217_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.User', verbose_name='员工'),
        ),
    ]
