# Generated by Django 2.2.3 on 2019-12-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0026_auto_20191219_1923'),
        ('meta', '0008_merge_20190812_0048'),
        ('account', '0004_workrecord_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.InAndOut', verbose_name='记录')),
                ('tollman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta.User', verbose_name='操作员')),
            ],
            options={
                'verbose_name': '特放记录',
                'verbose_name_plural': '特放记录',
            },
        ),
    ]
