# Generated by Django 2.2.3 on 2019-12-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_specrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='offline',
            field=models.DateTimeField(null=True, verbose_name='断线时间'),
        ),
    ]
