# Generated by Django 2.2.3 on 2019-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191220_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='specrecord',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='语音备注'),
        ),
    ]
