# Generated by Django 2.2.3 on 2019-11-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '激活'), (-1, '冻结')], default=0, verbose_name='状态')),
                ('name', models.CharField(max_length=30, verbose_name='商家名称')),
                ('account', models.CharField(max_length=30, unique=True, verbose_name='登录账号')),
                ('owner', models.CharField(max_length=30, verbose_name='联系人姓名')),
                ('phone', models.IntegerField(default=0, verbose_name='联系人电话')),
                ('balance', models.FloatField(default=0, verbose_name='余额')),
                ('duration', models.FloatField(default=0, verbose_name='时长')),
                ('type', models.IntegerField(choices=[(0, '无限制'), (1, '限制天'), (2, '限制周'), (3, '限制月')], default=0, verbose_name='限制类型')),
                ('rule', models.CharField(max_length=100, null=True, verbose_name='限制规则')),
                ('amount', models.IntegerField(default=0, verbose_name='限制张数')),
                ('descript', models.CharField(max_length=100, null=True, verbose_name='商家描述')),
            ],
            options={
                'verbose_name': '商户管理',
                'verbose_name_plural': '商户管理',
            },
        ),
    ]
