# Generated by Django 2.2.3 on 2019-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, '冻结'), (1, '激活')], default=0, verbose_name='状态'),
        ),
    ]
