# Generated by Django 2.2.3 on 2019-11-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20191128_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account',
            field=models.CharField(max_length=30, verbose_name='登录账号'),
        ),
    ]
