# Generated by Django 2.2.3 on 2019-11-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20191128_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, verbose_name='退款金额')),
                ('duration', models.FloatField(default=0, verbose_name='退款时长')),
                ('cost', models.FloatField(default=0, verbose_name='退还费用')),
                ('reason', models.CharField(max_length=100, verbose_name='退款原因')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
            },
        ),
    ]
