# Generated by Django 2.2.3 on 2019-11-28 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.IntegerField(choices=[(-1, '删除'), (0, '未审核'), (1, '已审核')], default=0, verbose_name='状态'),
        ),
    ]
