# Generated by Django 2.2.3 on 2019-12-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20191129_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default=0, max_length=30, verbose_name='联系人电话'),
        ),
    ]
